spring:
  application:
    name: application-name
  datasource:
    url: jdbc:h2:./target/test;DB_CLOSE_ON_EXIT=FALSE;
  security:
    user:
      name: actuator
      password: actuator
my:
  service:
    myProperty: foo

management:
  endpoints:
    web:
      base-path: /admin
  security:

info:
  build:
    artifact: ${artifactId}
    name: artifact-name
    description: service-description
    version: ${version}

swagger:
  base-package: ${groupId}.controller
  api-info:
    title: great-api
    description: My great API
    version: ${version}
    contact:
      name: Marcel Müller
      url: https://bitgrip.de
      email: marcel.mueller@bitgrip.de
